name: "hello added workflow"

on:
    push:
        branches:
            - master
  

    pull_request:
        branches:
            - master


jobs: 
    
    on-date:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "print date"
              run: date 
            
    on-pull:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request"
              run: echo "running on pull request"
            
    